### ISSUE TITLE
环境问题

### ISSUE THREAD

**Issue by CRLqinliang** [kaixindelele/RHER#4]
**系统**：Ubuntu 20.04/ RTX3090/CUDA12.0/Nvidia driver525.125.06
**以下是rher的Conda虚拟环境的list:**
```
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
_tflow_select             2.1.0                       gpu  
absl-py                   1.4.0                    pypi_0    pypi
astor                     0.8.1                    pypi_0    pypi
binutils_impl_linux-64    2.33.1               he6710b0_7  
binutils_linux-64         2.33.1              h9595d00_15  
blas                      1.0                         mkl  
bzip2                     1.0.8                h7b6447c_0  
c-ares                    1.19.0               h5eee18b_0  
ca-certificates           2023.05.30           h06a4308_0  
cairo                     1.16.0               hb05425b_5  
certifi                   2021.5.30        py36h06a4308_0  
cffi                      1.14.6           py36h400218f_0  
chardet                   4.0.0                    pypi_0    pypi
click                     8.0.3              pyhd3eb1b0_0  
cloudpickle               1.6.0                    pypi_0    pypi
cudatoolkit               10.1.243             h6bb024c_0  
cudnn                     7.6.5                cuda10.1_0  
cupti                     10.1.168                      0  
cycler                    0.11.0                   pypi_0    pypi
cython                    0.29.35                  pypi_0    pypi
dataclasses               0.8                pyh4f3eec9_6  
decorator                 4.4.2                    pypi_0    pypi
expat                     2.4.9                h6a678d5_0  
fasteners                 0.18                     pypi_0    pypi
ffmpeg                    4.0                  hcdf2ecd_0  
fontconfig                2.14.1               h4c34cd2_2  
freeglut                  3.0.0                hf484d3e_5  
freetype                  2.12.1               h4a9f257_0  
future                    0.18.3                   pypi_0    pypi
gast                      0.5.4                    pypi_0    pypi
gcc_impl_linux-64         7.3.0                habb00fd_1  
gcc_linux-64              7.3.0               h553295d_15  
glew                      2.1.0                h9c3ff4c_2    conda-forge
glfw                      2.0.0                    pypi_0    pypi
glib                      2.69.1               h4ff587b_1  
glob2                     0.7                      pypi_0    pypi
google-pasta              0.2.0              pyhd3eb1b0_0  
graphite2                 1.3.14               h295c915_1  
grpcio                    1.48.2                   pypi_0    pypi
gym                       0.18.0                   pypi_0    pypi
h5py                      2.8.0                    pypi_0    pypi
harfbuzz                  1.8.8                hffaf4a1_0  
hdf5                      1.10.2               hba1933b_1  
icu                       58.2                 he6710b0_3  
idna                      2.10                     pypi_0    pypi
imageio                   2.15.0                   pypi_0    pypi
importlib-metadata        4.8.3                    pypi_0    pypi
imutils                   0.5.4                    pypi_0    pypi
intel-openmp              2022.1.0          h9e868ea_3769  
ipython                   3.2.3                    pypi_0    pypi
jasper                    2.0.14               hd8c5072_2  
joblib                    1.0.1                    pypi_0    pypi
jpeg                      9e                   h5eee18b_1  
keras-applications        1.0.8                      py_1  
keras-preprocessing       1.1.2              pyhd3eb1b0_0  
kiwisolver                1.3.1                    pypi_0    pypi
ld_impl_linux-64          2.33.1               h53a641e_7  
lerc                      3.0                  h295c915_0  
libdeflate                1.17                 h5eee18b_0  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 11.2.0               h1234567_1  
libgfortran-ng            7.5.0               ha8ba4b0_17  
libgfortran4              7.5.0               ha8ba4b0_17  
libglu                    9.0.0                hf484d3e_1  
libgomp                   11.2.0               h1234567_1  
libopencv                 3.4.2                hb342d67_1  
libopus                   1.3.1                h7b6447c_0  
libpng                    1.6.39               h5eee18b_0  
libprotobuf               3.17.2               h4ff587b_1  
libstdcxx-ng              11.2.0               h1234567_1  
libtiff                   4.5.0                h6a678d5_2  
libuuid                   1.41.5               h5eee18b_0  
libvpx                    1.7.0                h439df22_0  
libwebp-base              1.2.4                h5eee18b_1  
libxcb                    1.15                 h7f8727e_0  
libxml2                   2.10.3               hcbfbd50_0  
llvmlite                  0.36.0                   pypi_0    pypi
lockfile                  0.12.2                   pypi_0    pypi
lz4-c                     1.9.4                h6a678d5_0  
markdown                  3.3.7                    pypi_0    pypi
matplotlib                3.3.4                    pypi_0    pypi
mesalib                   18.3.1               h590aaf7_0    conda-forge
mkl                       2020.2                      256  
mkl-service               2.3.0            py36he8ac12f_0  
mkl_fft                   1.3.0            py36h54f3939_0  
mkl_random                1.1.1            py36h0573a6f_0  
mpi4py                    3.0.3                    pypi_0    pypi
mujoco-py                 2.0.2.8                  pypi_0    pypi
ncurses                   6.4                  h6a678d5_0  
networkx                  2.5.1                    pypi_0    pypi
numba                     0.53.1                   pypi_0    pypi
numpy                     1.19.5                   pypi_0    pypi
numpy-base                1.19.2           py36hfa32c7d_0  
opencv                    3.4.2            py36h6fd60c2_1  
openssl                   1.1.1v               h7f8727e_0  
pandas                    1.1.5                    pypi_0    pypi
pcre                      8.45                 h295c915_0  
pillow                    8.4.0                    pypi_0    pypi
pip                       21.2.2           py36h06a4308_0  
pixman                    0.40.0               h7f8727e_1  
protobuf                  3.14.0                   pypi_0    pypi
psutil                    5.8.0                    pypi_0    pypi
py-opencv                 3.4.2            py36hb342d67_1  
pycparser                 2.21               pyhd3eb1b0_0  
pygame                    2.0.1                    pypi_0    pypi
pyglet                    1.5.0                    pypi_0    pypi
pyopengl                  3.1.1a1          py36h06a4308_0  
pyparsing                 3.1.1                    pypi_0    pypi
python                    3.6.13               h12debd9_1  
python-dateutil           2.8.2                    pypi_0    pypi
pytz                      2023.3                   pypi_0    pypi
pywavelets                1.1.1                    pypi_0    pypi
readline                  8.2                  h5eee18b_0  
requests                  2.25.1                   pypi_0    pypi
scikit-image              0.17.2                   pypi_0    pypi
scipy                     1.5.4                    pypi_0    pypi
seaborn                   0.8.1                    pypi_0    pypi
setuptools                58.0.4           py36h06a4308_0  
six                       1.16.0             pyhd3eb1b0_1  
sqlite                    3.41.2               h5eee18b_0  
tensorboard               1.14.0           py36hf484d3e_0  
tensorflow                1.14.0          gpu_py36h3fb9ad6_0  
tensorflow-base           1.14.0          gpu_py36he45bfe2_0  
tensorflow-estimator      1.14.0                     py_0  
tensorflow-gpu            1.14.0               h0d30ee6_0  
termcolor                 1.1.0                    pypi_0    pypi
tifffile                  2020.9.3                 pypi_0    pypi
tk                        8.6.12               h1ccaba5_0  
typing_extensions         4.1.1              pyh06a4308_0  
urllib3                   1.26.16                  pypi_0    pypi
werkzeug                  2.0.3              pyhd3eb1b0_0  
wheel                     0.37.1             pyhd3eb1b0_0  
wrapt                     1.15.0                   pypi_0    pypi
xorg-fixesproto           5.0               h7f98852_1002    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libx11               1.7.2                h7f98852_0    conda-forge
xorg-libxcursor           1.2.0                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h7f98852_1    conda-forge
xorg-libxfixes            5.0.3             h7f98852_1004    conda-forge
xorg-libxinerama          1.1.4             h9c3ff4c_1001    conda-forge
xorg-libxrandr            1.5.2                h7f98852_1    conda-forge
xorg-libxrender           0.9.10            h7f98852_1003    conda-forge
xorg-randrproto           1.5.0             h7f98852_1001    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-xextproto            7.3.0             h7f98852_1002    conda-forge
xorg-xproto               7.0.31            h27cfd23_1007  
xz                        5.4.2                h5eee18b_0  
zipp                      3.6.0              pyhd3eb1b0_0  
zlib                      1.2.13               h5eee18b_0  
zstd                      1.5.5                hc292b87_0 
```
**tensorflow gpu 工作正常**
```
>>> import tensorflow as tf
/home/qinliang/software/anaconda3/envs/rher/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/qinliang/software/anaconda3/envs/rher/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/qinliang/software/anaconda3/envs/rher/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/qinliang/software/anaconda3/envs/rher/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/qinliang/software/anaconda3/envs/rher/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/qinliang/software/anaconda3/envs/rher/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/home/qinliang/software/anaconda3/envs/rher/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/qinliang/software/anaconda3/envs/rher/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/qinliang/software/anaconda3/envs/rher/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/qinliang/software/anaconda3/envs/rher/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/qinliang/software/anaconda3/envs/rher/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/qinliang/software/anaconda3/envs/rher/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
>>> tf.test.is_gpu_available()
2023-08-04 16:37:55.316299: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2023-08-04 16:37:55.351418: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3393580000 Hz
2023-08-04 16:37:55.352626: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55e3f532b390 executing computations on platform Host. Devices:
2023-08-04 16:37:55.352650: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
2023-08-04 16:37:55.354310: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcuda.so.1
2023-08-04 16:37:55.431514: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-08-04 16:37:55.431708: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55e3f7c214d0 executing computations on platform CUDA. Devices:
2023-08-04 16:37:55.431727: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): NVIDIA GeForce RTX 3090, Compute Capability 8.6
2023-08-04 16:37:55.431889: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-08-04 16:37:55.432015: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties: 
name: NVIDIA GeForce RTX 3090 major: 8 minor: 6 memoryClockRate(GHz): 1.695
pciBusID: 0000:0b:00.0
2023-08-04 16:37:55.432175: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.1
2023-08-04 16:37:55.433431: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcublas.so.10
2023-08-04 16:37:55.434722: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcufft.so.10
2023-08-04 16:37:55.434907: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcurand.so.10
2023-08-04 16:37:55.436228: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusolver.so.10
2023-08-04 16:37:55.436967: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusparse.so.10
2023-08-04 16:37:55.439877: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
2023-08-04 16:37:55.439970: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-08-04 16:37:55.440129: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-08-04 16:37:55.440230: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1763] Adding visible gpu devices: 0
2023-08-04 16:37:55.440254: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.1
2023-08-04 16:37:55.440474: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181] Device interconnect StreamExecutor with strength 1 edge matrix:
2023-08-04 16:37:55.440483: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1187]      0 
2023-08-04 16:37:55.440489: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 0:   N 
2023-08-04 16:37:55.440562: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-08-04 16:37:55.440707: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-08-04 16:37:55.440825: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/device:GPU:0 with 20428 MB memory) -> physical GPU (device: 0, name: NVIDIA GeForce RTX 3090, pci bus id: 0000:0b:00.0, compute capability: 8.6)
True
>>> 
```
运行 ``` bash run_rher_push.sh ```的结果:
```
WARNING:tensorflow:From /home/qinliang/Desktop/RHER/RHER/baselines/common/tf_util.py:53: The name tf.get_default_session is deprecated. Please use tf.compat.v1.get_default_session instead.

WARNING:tensorflow:From /home/qinliang/Desktop/RHER/RHER/baselines/common/tf_util.py:70: The name tf.InteractiveSession is deprecated. Please use tf.compat.v1.InteractiveSession instead.

2023-08-04 16:39:21.159165: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2023-08-04 16:39:21.202122: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3393580000 Hz
2023-08-04 16:39:21.203106: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x558b08f11530 executing computations on platform Host. Devices:
2023-08-04 16:39:21.203138: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
2023-08-04 16:39:21.204954: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcuda.so.1
2023-08-04 16:39:21.210357: E tensorflow/stream_executor/cuda/cuda_driver.cc:318] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2023-08-04 16:39:21.210384: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: qinliang-Alienware-Aurora-Ryzen-Edition
2023-08-04 16:39:21.210390: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: qinliang-Alienware-Aurora-Ryzen-Edition
2023-08-04 16:39:21.210501: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 525.125.6
2023-08-04 16:39:21.210571: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 525.125.6
2023-08-04 16:39:21.210594: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:310] kernel version seems to match DSO: 525.125.6
WARNING:tensorflow:From /home/qinliang/Desktop/RHER/RHER/baselines/common/misc_util.py:58: The name tf.set_random_seed is deprecated. Please use tf.compat.v1.set_random_seed instead.
pygame 2.0.1 (SDL 2.0.14, Python 3.6.13)
Hello from the pygame community. https://www.pygame.org/contribute.html
args: ['/home/qinliang/Desktop/RHER/RHER/baselines/run_bash_rher.py', '--env', 'FetchPush-v1', '--seed', '0', '--gpu_id=-1', '--alg=rher']
seed: 100
env: FetchPush-v1
args: ['/home/qinliang/Desktop/RHER/RHER/baselines/run_bash_rher.py', '--env', 'FetchPush-v1', '--seed', '0', '--gpu_id=-1', '--alg=rher', '--log_path=/tmp/rher_results/rher_np19_case0_results/FetchPush-v1_RHER/FetchPush-v1_RHER_s100', '--num_cpu=19', '--num_env=1', '--num_timesteps=1.3e5', '--render=False']
env_type: robotics
rl_algs: rl_algs.rher.defaults
running build_ext
building 'mujoco_py.cymj' extension
/home/qinliang/software/anaconda3/envs/rher/bin/x86_64-conda_cos6-linux-gnu-cc -DNDEBUG -fwrapv -O2 -Wall -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/qinliang/software/anaconda3/envs/rher/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/qinliang/software/anaconda3/envs/rher/include -fPIC -I/home/qinliang/software/anaconda3/envs/rher/lib/python3.6/site-packages/mujoco_py -I/home/qinliang/.mujoco/mujoco200/include -I/home/qinliang/software/anaconda3/envs/rher/lib/python3.6/site-packages/numpy/core/include -I/home/qinliang/software/anaconda3/envs/rher/include/python3.6m -c /home/qinliang/software/anaconda3/envs/rher/lib/python3.6/site-packages/mujoco_py/cymj.c -o /home/qinliang/software/anaconda3/envs/rher/lib/python3.6/site-packages/mujoco_py/generated/_pyxbld_2.0.2.8_36_linuxcpuextensionbuilder/temp.linux-x86_64-3.6/home/qinliang/software/anaconda3/envs/rher/lib/python3.6/site-packages/mujoco_py/cymj.o -fopenmp -w
/home/qinliang/software/anaconda3/envs/rher/bin/x86_64-conda_cos6-linux-gnu-cc -DNDEBUG -fwrapv -O2 -Wall -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/qinliang/software/anaconda3/envs/rher/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/qinliang/software/anaconda3/envs/rher/include -fPIC -I/home/qinliang/software/anaconda3/envs/rher/lib/python3.6/site-packages/mujoco_py -I/home/qinliang/.mujoco/mujoco200/include -I/home/qinliang/software/anaconda3/envs/rher/lib/python3.6/site-packages/numpy/core/include -I/home/qinliang/software/anaconda3/envs/rher/include/python3.6m -c /home/qinliang/software/anaconda3/envs/rher/lib/python3.6/site-packages/mujoco_py/gl/osmesashim.c -o /home/qinliang/software/anaconda3/envs/rher/lib/python3.6/site-packages/mujoco_py/generated/_pyxbld_2.0.2.8_36_linuxcpuextensionbuilder/temp.linux-x86_64-3.6/home/qinliang/software/anaconda3/envs/rher/lib/python3.6/site-packages/mujoco_py/gl/osmesashim.o -fopenmp -w
x86_64-conda_cos6-linux-gnu-gcc -pthread -shared -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,-rpath,/home/qinliang/software/anaconda3/envs/rher/lib -L/home/qinliang/software/anaconda3/envs/rher/lib -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,-rpath,/home/qinliang/software/anaconda3/envs/rher/lib -L/home/qinliang/software/anaconda3/envs/rher/lib -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath,/home/qinliang/software/anaconda3/envs/rher/lib -Wl,-rpath-link,/home/qinliang/software/anaconda3/envs/rher/lib -L/home/qinliang/software/anaconda3/envs/rher/lib -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/qinliang/software/anaconda3/envs/rher/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/qinliang/software/anaconda3/envs/rher/include /home/qinliang/software/anaconda3/envs/rher/lib/python3.6/site-packages/mujoco_py/generated/_pyxbld_2.0.2.8_36_linuxcpuextensionbuilder/temp.linux-x86_64-3.6/home/qinliang/software/anaconda3/envs/rher/lib/python3.6/site-packages/mujoco_py/cymj.o /home/qinliang/software/anaconda3/envs/rher/lib/python3.6/site-packages/mujoco_py/generated/_pyxbld_2.0.2.8_36_linuxcpuextensionbuilder/temp.linux-x86_64-3.6/home/qinliang/software/anaconda3/envs/rher/lib/python3.6/site-packages/mujoco_py/gl/osmesashim.o -L/home/qinliang/.mujoco/mujoco200/bin -Wl,-R/home/qinliang/.mujoco/mujoco200/bin -lmujoco200 -lglewosmesa -lOSMesa -lGL -o /home/qinliang/software/anaconda3/envs/rher/lib/python3.6/site-packages/mujoco_py/generated/_pyxbld_2.0.2.8_36_linuxcpuextensionbuilder/lib.linux-x86_64-3.6/mujoco_py/cymj.cpython-36m-x86_64-linux-gnu.so -fopenmp
/home/qinliang/software/anaconda3/envs/rher/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: cannot find -lOSMesa
/home/qinliang/software/anaconda3/envs/rher/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: cannot find -lGL
collect2: error: ld returned 1 exit status
Traceback (most recent call last):
  File "/home/qinliang/software/anaconda3/envs/rher/lib/python3.6/distutils/unixccompiler.py", line 197, in link
    self.spawn(linker + ld_args)
  File "/home/qinliang/software/anaconda3/envs/rher/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/home/qinliang/software/anaconda3/envs/rher/lib/python3.6/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/home/qinliang/software/anaconda3/envs/rher/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'x86_64-conda_cos6-linux-gnu-gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/qinliang/software/anaconda3/envs/rher/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/qinliang/software/anaconda3/envs/rher/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/qinliang/Desktop/RHER/RHER/baselines/run_bash_rher.py", line 286, in <module>
    main(sys.argv)
  File "/home/qinliang/Desktop/RHER/RHER/baselines/run_bash_rher.py", line 225, in main
    model, env = train(args, extra_args)
  File "/home/qinliang/Desktop/RHER/RHER/baselines/run_bash_rher.py", line 66, in train
    env = build_env(args)
  File "/home/qinliang/Desktop/RHER/RHER/baselines/run_bash_rher.py", line 118, in build_env
    flatten_dict_observations=flatten_dict_observations)
  File "/home/qinliang/Desktop/RHER/RHER/baselines/common/cmd_util.py", line 59, in make_vec_env
    return DummyVecEnv([make_thunk(i + start_index, initializer=None) for i in range(num_env)])
  File "/home/qinliang/Desktop/RHER/RHER/baselines/common/vec_env/dummy_vec_env.py", line 19, in __init__
    self.envs = [fn() for fn in env_fns]
  File "/home/qinliang/Desktop/RHER/RHER/baselines/common/vec_env/dummy_vec_env.py", line 19, in <listcomp>
    self.envs = [fn() for fn in env_fns]
  File "/home/qinliang/Desktop/RHER/RHER/baselines/common/cmd_util.py", line 52, in <lambda>
    initializer=initializer
  File "/home/qinliang/Desktop/RHER/RHER/baselines/common/cmd_util.py", line 81, in make_env
    env = gym.make(env_id, **env_kwargs)
  File "/home/qinliang/Desktop/RHER/RHER/gym/envs/registration.py", line 145, in make
    return registry.make(id, **kwargs)
  File "/home/qinliang/Desktop/RHER/RHER/gym/envs/registration.py", line 90, in make
    env = spec.make(**kwargs)
  File "/home/qinliang/Desktop/RHER/RHER/gym/envs/registration.py", line 59, in make
    cls = load(self.entry_point)
  File "/home/qinliang/Desktop/RHER/RHER/gym/envs/registration.py", line 18, in load
    mod = importlib.import_module(mod_name)
  File "/home/qinliang/software/anaconda3/envs/rher/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/qinliang/Desktop/RHER/RHER/gym/envs/robotics/__init__.py", line 1, in <module>
    from gym.envs.robotics.fetch_env import FetchEnv
  File "/home/qinliang/Desktop/RHER/RHER/gym/envs/robotics/fetch_env.py", line 3, in <module>
    from gym.envs.robotics import rotations, robot_env, utils
  File "/home/qinliang/Desktop/RHER/RHER/gym/envs/robotics/robot_env.py", line 10, in <module>
    import mujoco_py
  File "/home/qinliang/software/anaconda3/envs/rher/lib/python3.6/site-packages/mujoco_py/__init__.py", line 3, in <module>
    from mujoco_py.builder import cymj, ignore_mujoco_warnings, functions, MujocoException
  File "/home/qinliang/software/anaconda3/envs/rher/lib/python3.6/site-packages/mujoco_py/builder.py", line 506, in <module>
    cymj = load_cython_ext(mujoco_path)
  File "/home/qinliang/software/anaconda3/envs/rher/lib/python3.6/site-packages/mujoco_py/builder.py", line 105, in load_cython_ext
    cext_so_path = builder.build()
  File "/home/qinliang/software/anaconda3/envs/rher/lib/python3.6/site-packages/mujoco_py/builder.py", line 221, in build
    built_so_file_path = self._build_impl()
  File "/home/qinliang/software/anaconda3/envs/rher/lib/python3.6/site-packages/mujoco_py/builder.py", line 273, in _build_impl
    so_file_path = super()._build_impl()
  File "/home/qinliang/software/anaconda3/envs/rher/lib/python3.6/site-packages/mujoco_py/builder.py", line 244, in _build_impl
    dist.run_commands()
  File "/home/qinliang/software/anaconda3/envs/rher/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/qinliang/software/anaconda3/envs/rher/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/qinliang/software/anaconda3/envs/rher/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/home/qinliang/software/anaconda3/envs/rher/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/home/qinliang/software/anaconda3/envs/rher/lib/python3.6/site-packages/mujoco_py/builder.py", line 144, in build_extensions
    build_ext.build_extensions(self)
  File "/home/qinliang/software/anaconda3/envs/rher/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "/home/qinliang/software/anaconda3/envs/rher/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/home/qinliang/software/anaconda3/envs/rher/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/qinliang/software/anaconda3/envs/rher/lib/python3.6/distutils/command/build_ext.py", line 558, in build_extension
    target_lang=language)
  File "/home/qinliang/software/anaconda3/envs/rher/lib/python3.6/distutils/ccompiler.py", line 717, in link_shared_object
    extra_preargs, extra_postargs, build_temp, target_lang)
  File "/home/qinliang/software/anaconda3/envs/rher/lib/python3.6/distutils/unixccompiler.py", line 199, in link
    raise LinkError(msg)
distutils.errors.LinkError: command 'x86_64-conda_cos6-linux-gnu-gcc' failed with exit status 1
```

**Comment by CRLqinliang** [comment]
能查到的方法都试了... 我换gym的环境得了

**Comment by CRLqinliang** [comment]
Thanks!
